### ISSUE TITLE
Modbus Error: [Input/Output] No Response received from the remote slave/Unable to decode response

### ISSUE THREAD

**Issue by joseph112** [pymodbus-dev/pymodbus#2371]
The instruction I sent was that RTU should respond with 8 bits, but the program calculates it as 7 bits.
The correct input and response is as follows
send: 01 03 FA 0C 00 01 74 D1
rec: 01 03 00 02 23 2C FC E7
Here's the translation:

I modified `self.base_adu_size` to be `address(2)`, making `self.base_adu_size = 4`. The response length indeed became 8 bits. However, `self.transactions` remains empty or throws the same error. What should I do?

**Comment by joseph112** [comment]
My test code is as follows
```
from pymodbus.client import ModbusSerialClient

client = ModbusSerialClient(port="COM1", baudrate=38400)
if client.connect():
    print("The connection was successful.")
else:
    print("Failed to connect")
result = client.read_holding_registers(address=64012, count=1, slave=1)
if result.isError:
    print(result)
else:
    print(result.registers)
client.close()
```

**Comment by janiversen** [comment]
You are reading a holding register, which is a register not bits. A register is defined by the standard to be 2bytes.

for bits use a bit function like e.g. read_coils, that will deliver the bits requested rounded up to bytes as pr standard.

**Comment by janiversen** [comment]
And just for information:
```
send: 01 03 FA 0C 00 01 74 D1
rec: 01 03 00 02 23 2C FC E7
```

The send asks for 1 registers (00 01)
and your device responds with length 2 bytes (00 02) == 1 register so you get 1 register back with the value (23 2c)

that is all correct, but has nothing to do with bits.

**Comment by joseph112** [comment]
Regarding the instruction length, it includes both the high and low bits separately. Another issue is why self.transactions is empty, leading to "No Response received from the remote slave / Unable to decode response".

**Comment by janiversen** [comment]
I have no idea what you talk about! your modifications are wrong, mainly because because you use a call that always will return a multiple of 16 bits.

Stay assured the function call you use, work as it should do...and as you saw in my analysis you get the correct answer corresponding to the request you make.

**Comment by janiversen** [comment]
If you doubt that read_holding_register should always return a multiple of 16bits == number of register x 2, then please read the modbus standard.

As I said earlier if you want bits the use a bit call....this is also described in the standard.

**Comment by joseph112** [comment]
I'm sorry I didn't get it clear. I mean why using the pymodbus library it only returns an error, whereas I use other tools it is correct.
![Uploading 234.JPG…]()

**Comment by janiversen** [comment]
What I tried to say is that pymodbus works without your modifications it will return the same as the other tool.....which also returns 16bit.

Don't blame pymodbus blame your wrong changes.

**Comment by joseph112** [comment]
I did not modify it, using it directly will return an error. It is correct with other tools. Other tools are shown in the screenshot above.

**Comment by janiversen** [comment]
hmm your text says "I modified self.base_adu_size to be address(2), making self.base_adu_size = 4. The response length indeed became 8 bits. However, self.transactions remains empty or throws the same error. What should I do?"

You also wrote "The instruction I sent was that RTU should respond with 8 bits" but read_holding_register respond with a multiple of 16 bits.

**Comment by janiversen** [comment]
If you want help, you need to add a debug log, with a not modified pymodbus !! so we can see what your problem might be !

With the debug log we can see exactly what is being sent and what is being received.

**Comment by joseph112** [comment]
Sorry, I tried modifying the base_adu_size, but it always returned the same error, so I reset it.

**Comment by janiversen** [comment]
I think you are not talking about BITS but BYTES (a BYTE is 8 BITS), that at least explains a lot.

Yes pymodbus do not receive the last BYTE, probably because your usb does not deliver it im time.

Which version of pymodbus are you using ? this should be solved in v3.7.3

**Comment by janiversen** [comment]
When pymodbus does not receive a full frame, it will try to read again….that does not happen in your example, so I think you are using an old version.

**Comment by janiversen** [comment]
Try to set timeout=5 that will make the receiver wait for 5 seconds before retrying.

**Comment by joseph112** [comment]
I apologize, my description contained an error; indeed, I was referring to bytes. The version of pymodbus is: 3.7.3

**Comment by joseph112** [comment]
This is my test code, the error still exists.
`from pymodbus.client import ModbusSerialClient

client = ModbusSerialClient(port="COM1", baudrate=38400, framer=FramerType.RTU, timeout=5)
if client.connect():
    print("The connection was successful.")
else:
    print("Failed to connect")
result = client.read_holding_registers(address=64012, count=1, slave=1)
if result.isError:
    print(result)
else:
    print(result.registers)
client.close()`

**Comment by janiversen** [comment]
please add retries=10, I just now saw that you are using the sync. version, which have a different implementation (old, and more limited than the async version).

AND please add the debug log, so I can see the effect.

**Comment by joseph112** [comment]
I tried retries=10 but it still doesn't work. I'm not quite sure what you mean, are you asking me to try the old version or the asynchronous version?

**Comment by janiversen** [comment]
The sync version is in maintenance mode, pending a major rewrite, so a number of the features is not available.

the async version uses both retries= and timeout=

I am not sure what you mean by "old version", I did not talk about that.

I am preparing a bug fix to the sync version, that implements timeout= for receive.

**Comment by joseph112** [comment]
Thank you very much, I understand.

**Comment by janiversen** [comment]
Now I did a bit more analyzing and testing....you claim the correct response is:
```
01 03 00 02 23 2C FC E7
```
First byte is slave_id and the 2 last bytes are CRC, so the PDU is:
```
03 00 02 23 2C
```
The modbus standard defined function code 0x03 as:
![Captura de pantalla 2024-10-14 a las 12 48 24](https://github.com/user-attachments/assets/b79a0fbd-c4d2-432b-b238-809c96d6c82a)

So decoding the PDU:
03 = Function code
00 = 2 x N, where N is number of registers
02 23 2c = Data which is should be a multiple of 2 (since a register is 2 bytes).

As you can see your device responds with a wrong byte count, and that is the real problem, why you do not receive anything.

**Comment by janiversen** [comment]
There are however a bug in the sync code, which I still have to fix.

**Comment by joseph112** [comment]
I used this code to test the asynchronous client, but the error still persists.
https://github.com/pymodbus-dev/pymodbus/blob/dev/examples/simple_async_client.py

**Comment by janiversen** [comment]
Yes because the message your device sends (count = 0) is not correct.

**Comment by joseph112** [comment]
02 is the data number, 23 2C is the returned data.

**Comment by joseph112** [comment]
My device's error frame returns 01 03 80 01 00 04 3C 09

**Comment by joseph112** [comment]
I feel that the data frame returned by my device, the data length should occupy two bytes.

**Comment by janiversen** [comment]
Look at the standard, I sent you !!! data length is 1 byte NOT 2.

**Comment by joseph112** [comment]
I consulted with the device manufacturer, and they informed me that Modbus is not a standard; data length spans 2 bytes. Therefore, the data length for 00 02 bits.

**Comment by janiversen** [comment]
Modbus is a standard, a very official standard, but it seems your device is not following the modbus standard.

Pymodbus support the modbus standard, and not vendor variations, so please use another library.
