### ISSUE TITLE
Async TCP Server opens too many file descriptors on repeated client connect

### ISSUE THREAD

**Issue by Doeme** [pymodbus-dev/pymodbus#2462]
### Versions

- Python: 3.12.3
- OS: Ubuntu 24.04.1 LTS
- Pymodbus: 3.7.4
- Modbus Hardware (if used): None

### Pymodbus Specific

- Server: tcp - async
- Client: tcp - sync

### Description

After a while of running, the async server stops responding, because of "too many open files"

### Code and Logs

```python
# Server
import pymodbus

pymodbus.pymodbus_apply_logging_config("DEBUG")

from pymodbus.datastore.context import ModbusSequentialDataBlock
from pymodbus.datastore import ModbusServerContext, ModbusSlaveContext
from pymodbus.server import ModbusTcpServer
import asyncio


data = ModbusSequentialDataBlock(1, [0] * 32)
slaveContext = ModbusSlaveContext(di=data)
context = ModbusServerContext(slaveContext, single=True)

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

async def run_forever():
	server = ModbusTcpServer(context, address=("0.0.0.0", 5002))
	await server.serve_forever()

loop.run_until_complete(run_forever())
```

```python
#Client

from pymodbus.client import ModbusTcpClient
import time

for i in range(2048):
	client = ModbusTcpClient('localhost',port=5002)   # Create client object
	client.connect()                           # connect to device
	result = client.read_coils(2, 3, slave=1)  # get information from device
	print(result.bits[0])                      # use information
	client.close()                             # Disconnect device
	if i == 1024:
		time.sleep(1.5)
```

```
OSError: [Errno 24] Too many open files
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=6, family=2, type=1, proto=6, laddr=('0.0.0.0', 5002)>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 178, in _accept_connection
  File "/usr/lib/python3.12/socket.py", line 295, in accept
```

### Pointers

Why are sockets that are actively being closed being listened on here https://github.com/pymodbus-dev/pymodbus/blob/dev/pymodbus/transport/transport.py#L292 ?

The filedescriptor backing the transport should be the fd returned by accept(2)-ing on the server-socket  (which is the one that is listened on), and this former should not be listened on, right?

In any case, if we remove the do_relisten()-routine, the problem goes away while not impairing the functionality.

**Comment by janiversen** [comment]
The lines you are referring to are in the connection_lost callback, which are called whenever a client disconnects or the OS terminates the listener.

**Comment by samskiter** [comment]
We are seeing issues opening the modbus connectin - we suspect because a file handle is being left open (using serial transport instead of TCP though) would the lines highlighted in this issue potentially explain this behaviour?)

**Comment by janiversen** [comment]
Which lines? I find nothing highlighted.

Do you experience issues after a couple of connects (which would be a bug) or after thousands of connect, (which would be a production server, which might have other problems like memory leaks).

Removing do_reconnect_listen sounds like a bad option to me, because it would e.g mean unplugging the usb terminates the server. Better find find which file handles are not closed....it must be the client connections, because they are many while listen is only one.

**Comment by janiversen** [comment]
Just did a test:
- client connect
- readCoils
- client disconnect

in a loop running 100 times, and without any problems....so there might be a problem with socket not being closed, but it does not affect normal run of the server.

However it is still interesting to see if you found a bug.

**Comment by janiversen** [comment]
Did another test with your test program, modified to be correct (the read call was incorrect):
```
#!/usr/bin/env python3
"""Test server open files."""

from pymodbus.client import ModbusTcpClient
import time

for i in range(2048):
    client = ModbusTcpClient('localhost',port=5002)   # Create client object
    client.connect()                           # connect to device
    result = client.read_coils(address=2, count=3, slave=1)  # get information from device
    print(result.bits[0])                      # use information
    client.close()                             # Disconnect device
    if i == 1024:
        time.sleep(1.5)
```


Client log:
```
Not connected, trying to connect!
True
```
Repeated but no errors reported.


server log:
```
./server_async.py --comm tcp --port 5002 
2024-11-24 13:41:35,655 INFO  async_io:302 Server listening.
```


So pymodbus handles 2048 client connect/disconnect without any problems, therefore closing as "not a pymodbus problem".

**Comment by Doeme** [comment]
> Did another test with your test program, modified to be correct (the read call was incorrect):

Why was it incorrect, and how was it changed? The only delta apart from the header and indentation type is:
```
7c10
<     result = client.read_coils(2, 3, slave=1)  # get information from device
---
>     result = client.read_coils(address=2, count=3, slave=1)  # get information from device
```

And according to the read_coils header below, these two should afaict be equivalent?

```
def read_coils(self, address: int, count: int = 1, slave: int = 1, no_response_expected: bool = False) -> T
```

> Client log:
> ```
> Not connected, trying to connect!
> True
> ```

I'm a bit confused about that, as the server implementation I've posted above is supposed to return False, and I've no idea where `Not connected, trying to connect` is coming from.

> So pymodbus handles 2048 client connect/disconnect without any problems, therefore closing as "not a pymodbus problem".

I copy-pasted your client, added some more debugging to it, and still get the same behaviour. Scripts pasted, logs of a trial run attached.

## Server

```
# Server
import pymodbus

pymodbus.pymodbus_apply_logging_config("DEBUG")

from pymodbus.datastore.context import ModbusSequentialDataBlock
from pymodbus.datastore import ModbusServerContext, ModbusSlaveContext
from pymodbus.server import ModbusTcpServer
import asyncio


data = ModbusSequentialDataBlock(1, [0] * 32)
slaveContext = ModbusSlaveContext(di=data)
context = ModbusServerContext(slaveContext, single=True)

loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)

async def run_forever():
	server = ModbusTcpServer(context, address=("0.0.0.0", 5002))
	await server.serve_forever()

loop.run_until_complete(run_forever())
```
## Client

```
#!/usr/bin/env python3
"""Test server open files."""

import pymodbus

pymodbus.pymodbus_apply_logging_config("DEBUG")

from pymodbus.client import ModbusTcpClient
import time

for i in range(2048):
    client = ModbusTcpClient('localhost',port=5002)   # Create client object
    client.connect()                           # connect to device
    result = client.read_coils(address=2, count=3, slave=1)  # get information from device
    print(result.bits[0])                      # use information
    client.close()                             # Disconnect device
    if i == 1024:
        time.sleep(1.5)
```

## Logs

[logs.zip](https://github.com/user-attachments/files/17899231/logs.zip)

**Comment by janiversen** [comment]
> Why was it incorrect, and how was it changed? The only delta apart from the header and indentation type is:

Just look at the delta, count is a keyword parameter, if you used dev your call would have been illegal.

> I'm a bit confused about that, as the server implementation I've posted above is supposed to return False

Make a debug log, and you will see that the bit in the response is set.
 
Your server definition does not define coils, so why do you assume it is to be false.

> and I've no idea where `Not connected, trying to connect` is coming from.

Look in the code.

> I copy-pasted your client, added some more debugging to it, and still get the same behaviour. Scripts pasted, logs of a trial run attached.

I cannot tell you why you have the error, try with dev.

What I can tell you, is that on my Mac mini, it works (as shown with the copied logs), so it is very unlikely it will not work on ubuntu.

But most importantly, as written before the server is thought of as a test tool, not a production tool, and in test it is very unlikely to make 2048 connections....

Feel free to submit a pull request if you want to have changes, but please without e.g. removing the reconnect_listen, which is an important feature.

**Comment by janiversen** [comment]
From now on, we are testing that the server do not forget to close file descriptors, it is being tested on windows/ubuntu and macOS with every pull request.

For some reason you do not use "StartAsyncTcpServer"

you have some funny lines regarding the loop, I am not sure if that could have a negative influence, at least it is not the way we normally start async.

**Comment by Doeme** [comment]
The dev branch does, in deed, not show said behaviour. Bisecting reveals that the issue was fixed with ea326725d1a4d18c5bb30777be50b36d91d77ab3

**Comment by janiversen** [comment]
Of course, it is a feature of pymodbus that is has automatic reconnect for clients and relisten for servers. If a consumer makes a connect/listen in the callback (which itself is not easy, since a connect is async) then it's connected/listened on, and ?????

**Comment by samskiter** [comment]
I think it *was* the case that a retry count could cause a reconnect AND an exception to be thrown, which would further up signal to the callee that they they have become disconnected.... possibly fixed in here? https://github.com/pymodbus-dev/pymodbus/pull/2347/files

**Comment by samskiter** [comment]
In fact, perhaps I'm starting to form a theory here...

1. we hit retry limit [here](https://github.com/pymodbus-dev/pymodbus/blob/b0deefca07f522d35fc48fb9b09e6eae5cc56ea6/pymodbus/client/base.py#L123)
2. That BOTH starts a reconnection task [here](https://github.com/pymodbus-dev/pymodbus/blob/b0deefca07f522d35fc48fb9b09e6eae5cc56ea6/pymodbus/transport/transport.py#L288) AND then throws an exception which is thrown all the way up out of pymodbus
3. consumer exception handling says 'well I got an exception, that's exceptional, maybe I'll just retry with a new client'
4. Pymodbus old client is still firing off a task from (2) and so has not released the file handle when the new client is trying to grab it.


I'm not 100% sure on this, but does that sound feasible as a failure mode to you?

**Comment by janiversen** [comment]
I am confused with a couple of your points:
1: that is client code.
2: we talk about the server it does not do reconnect but only relisten.
3: a server do not have consumer exception handling
4: it`s still not server.


Are you now saying the not closed file descriptors are in the client and not the server '

**Comment by samskiter** [comment]
I think I'm seeing issues with the client yes, but found this issue tk be
potentially relevant

**Comment by janiversen** [comment]
Hmmm the title says "server" not client.

@samskiter The code shown creates a new client in the loop, so that can never have too many open file descriptors !

Apart from that @Doeme have confirmed this issue is solved. If you have problems with a client open too many file descriptors, then please open a new issue with example code etc.
